#!/usr/bin/python3
##############################################
#
# This is open source software licensed unter the Apache License 2.0
# http://www.apache.org/licenses/LICENSE-2.0
#
##############################################

from plantgw import PlantGateway


def main():
    pg = PlantGateway()
    pg.process_all()

if __name__ == '__main__':
    main()
